/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {

    public final static String DB_CONNECTION="jdbc:mysql://localhost:4589/demo_db";
    private final static String USERNAME = "root";
    private final static String PASSWORD = "root123";
    
    public static Connection getConnection() {

        //Loading database driver 
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        }catch(ClassNotFoundException ex){
            System.out.println("Error while loading DB driver");
        }

        Connection connection = null;
        try{
            connection = DriverManager.getConnection(DB_CONNECTION,USERNAME,PASSWORD);
        }catch(SQLException e){
            e.printStackTrace();
        }

        return connection;    
        
    }
}

